---

#- name: add wal-e symlink
#  file:
#    src: /opt/rh/{{ scl_python_version }}/root/usr/bin/wal-e
#    dest: /usr/bin/wal-e
#    state: link
##    force=yes

- name: create env dir
  file:
    path: /etc/wal-e.d/env
    state: directory

- name: copy wal-e settings files
  template:
    src: '{{ item }}'
    dest: /etc/wal-e.d/env/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - WALE_S3_ENDPOINT
    - WALE_S3_PREFIX

- name: create daily backup cronjob
  cron:
    name: daily postgres backup
    special_time: daily
    user: postgres
    job: envdir /etc/wal-e.d/env /usr/bin/wal-e backup-push /var/lib/pgsql/{{ wale_postgresql_version }}/data
  when: wale_cronjob | bool

#- name: add symlink for lib
#  file:
#    src: /opt/rh/rh-python35/root/usr/lib64/libpython3.5m.so.rh-python35-1.0
#    dest: /usr/lib64/libpython3.5m.so.rh-python35-1.0
#    state: link
#  when: ansible_os_family == "RedHat"
