---

- name: epel release
  package:
    state: present
    name: epel-release
    update_cache: true

- name: packages
  package:
    name: '{{ wale_rpm_packages }}'
    state: present

#    - name: install centos-release-scl
#      package:
#        name: centos-release-scl
#        state: present
#
#    - name: enable repo
#      shell: yum-config-manager --enable centos-sclo-rh-testing
#
#    - name: install {{ scl_python_version }}
#      package:
#        name: '{{ scl_python_version }}'
#        state: present

#- name: upgrade pip3 to latest version
#  shell: /opt/rh/{{ scl_python_version }}/root/usr/bin/pip3 install --upgrade pip
#  environment:
#    - LD_LIBRARY_PATH: /opt/rh/{{ scl_python_version }}/root/usr/lib64
#
#- name: add pip3 symlink
#  file:
#    src: /opt/rh/{{ scl_python_version }}/root/usr/bin/pip3
#    dest: /usr/bin/pip3
#    state: link
##      force=yes

#- name: wal-e install
#  pip:
#    name: '{{ item }}'
#  executable: /usr/bin/pip3
#  environment:
#    - LD_LIBRARY_PATH: /opt/rh/{{ scl_python_version }}/root/usr/lib64
#  with_items:
#    - wal-e[aws]

- name: install wal-e
  pip:
    name: wal-e[aws]
    executable: pip3

- name: install envdir
  easy_install:
    name: envdir
